# Generated by Django 4.2.16 on 2024-09-21 18:29

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("blog", "0002_blog_enabled"),
    ]

    operations = [
        migrations.CreateModel(
            name="BlogComments",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("Comments", models.TextField()),
                ("blog", models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to="blog.blog")),
            ],
        ),
    ]
