# Generated by Django 4.2.14 on 2024-09-06 18:57

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("blog", "0002_blog_enabled"),
    ]

    operations = [
        migrations.AlterField(
            model_name="blog",
            name="body",
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name="blog",
            name="category",
            field=models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, to="blog.category"),
        ),
        migrations.AlterField(
            model_name="blog",
            name="slug",
            field=models.SlugField(blank=True, max_length=255, unique=True),
        ),
    ]
