# Generated by Django 4.2.16 on 2024-09-21 19:29

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("blog", "0003_blogcomments"),
    ]

    operations = [
        migrations.AlterField(
            model_name="blogcomments",
            name="blog",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, related_name="comments", to="blog.blog"
            ),
        ),
    ]
