# Generated by Django 4.2.14 on 2024-09-06 19:20

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("blog", "0003_comments"),
    ]

    operations = [
        migrations.AddField(
            model_name="comments",
            name="text",
            field=models.TextField(default=0),
            preserve_default=False,
        ),
    ]
