# Generated by Django 4.2.14 on 2024-09-06 19:34

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("blog", "0004_comments_text"),
    ]

    operations = [
        migrations.RenameModel(
            old_name="Comments",
            new_name="Comment",
        ),
    ]
