# Generated by Django 4.2.14 on 2024-09-07 08:23

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("blog", "0005_rename_comments_comment"),
    ]

    operations = [
        migrations.AlterField(
            model_name="blog",
            name="enabled",
            field=models.BooleanField(),
        ),
    ]
