# Generated by Django 4.2.14 on 2024-09-07 09:57

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("blog", "0006_alter_blog_enabled"),
    ]

    operations = [
        migrations.RenameField(
            model_name="comment",
            old_name="text",
            new_name="body",
        ),
    ]
